import { ArrowDown, ArrowUp, Clock, Copy, GitBranch, Plus, Route, Trash2 } from "lucide-react";
import { useState } from "react";
import { buttonLabel, newId, type AutonomousProgram, type Program, type Project, type Step, type GamepadButton, type Binding } from "../core";

export const BUTTONS:GamepadButton[]=["a","b","x","y","left_bumper","right_bumper","dpad_up","dpad_down","dpad_left","dpad_right","back","start","left_stick_button","right_stick_button"];
export function NumberField({label,value,onChange,min,max,step=1}:{label:string;value:number;onChange:(n:number)=>void;min?:number;max?:number;step?:number}){return <label>{label}<input type="number" value={Number.isFinite(value)?value:0} min={min} max={max} step={step} onChange={e=>{if(Number.isFinite(e.target.valueAsNumber))onChange(e.target.valueAsNumber);}}/></label>;}
function cloneStep(step:Step):Step{return {...step,id:newId("step"),...("steps" in step?{steps:step.steps.map(cloneStep)}:{})};}
export function ProgramEditor({project,program,onChange}:{project:Project;program:Program;onChange:(p:Program)=>void}){
  return program.kind==="autonomous"?<Routine project={project} program={program} onChange={onChange}/>:<div className="editor-scroll"><h2>Drive controls</h2><div className="form-grid"><label className="check"><input type="checkbox" checked={program.drive.fieldCentric} onChange={e=>onChange({...program,drive:{...program.drive,fieldCentric:e.target.checked}})}/>Field-centric drive</label><NumberField label="Slow mode scale" value={program.drive.slowModeScale} min={0.01} max={1} step={0.05} onChange={n=>onChange({...program,drive:{...program.drive,slowModeScale:n}})}/>{(["slowModeButton","resetHeadingButton"] as const).map(key=><label key={key}>{key==="slowModeButton"?"Slow mode button":"Reset heading button"}<select value={program.drive[key]??""} onChange={e=>onChange({...program,drive:{...program.drive,[key]:e.target.value||null}})}><option value="">None</option>{BUTTONS.map(b=><option key={b} value={b}>{buttonLabel(b)}</option>)}</select></label>)}</div><h2>Gamepad bindings</h2><p>Assign buttons to mechanism states. Add mechanisms in Robot first.</p>{program.bindings.map((binding,index)=><div className="binding-row" key={binding.id}><select aria-label={`Gamepad ${index+1}`} value={binding.gamepad} onChange={e=>onChange({...program,bindings:program.bindings.map(b=>b.id===binding.id?{...b,gamepad:Number(e.target.value) as 1|2}:b)})}><option value="1">Gamepad 1</option><option value="2">Gamepad 2</option></select><select aria-label={`Button ${index+1}`} value={binding.button} onChange={e=>onChange({...program,bindings:program.bindings.map(b=>b.id===binding.id?{...b,button:e.target.value as GamepadButton}:b)})}>{BUTTONS.map(b=><option key={b} value={b}>{buttonLabel(b)}</option>)}</select><BindingActionEditor project={project} binding={binding} onChange={action=>onChange({...program,bindings:program.bindings.map(b=>b.id===binding.id?{...b,action}:b)})}/><button aria-label={`Delete binding ${index+1}`} onClick={()=>onChange({...program,bindings:program.bindings.filter(b=>b.id!==binding.id)})}><Trash2/></button></div>)}<button disabled={!project.subsystems.some(s=>s.states.length)} onClick={()=>{const s=project.subsystems.find(s=>s.states.length)!;onChange({...program,bindings:[...program.bindings,{id:newId("binding"),gamepad:1,button:"a",action:{kind:"state",subsystemId:s.id,stateId:s.states[0].id}}]});}}><Plus/>Add binding</button></div>;
}
function BindingActionEditor({project,binding,onChange}:{project:Project;binding:Binding;onChange:(a:Binding["action"])=>void}){
 const a=binding.action,s=project.subsystems.find(s=>s.id===a.subsystemId),states=s?.states??[];
 return <><select aria-label="Binding behavior" value={a.kind} onChange={e=>onChange(e.target.value==="state"?{kind:"state",subsystemId:a.subsystemId,stateId:states[0]?.id??""}:e.target.value==="hold"?{kind:"hold",subsystemId:a.subsystemId,heldStateId:states[0]?.id??"",releasedStateId:states[1]?.id??states[0]?.id??""}:{kind:"toggle",subsystemId:a.subsystemId,firstStateId:states[0]?.id??"",secondStateId:states[1]?.id??states[0]?.id??""})}><option value="state">On press</option><option value="toggle">Toggle</option><option value="hold">While held</option></select><select aria-label="Binding mechanism" value={a.subsystemId} onChange={e=>{const s=project.subsystems.find(s=>s.id===e.target.value)!;onChange({kind:"state",subsystemId:s.id,stateId:s.states[0]?.id??""});}}>{project.subsystems.map(s=><option key={s.id} value={s.id}>{s.name}</option>)}</select>{(a.kind==="state"?["stateId"]:a.kind==="toggle"?["firstStateId","secondStateId"]:["heldStateId","releasedStateId"]).map(key=><select aria-label={key} key={key} value={a[key as keyof typeof a]} onChange={e=>onChange({...a,[key]:e.target.value})}>{states.map(s=><option key={s.id} value={s.id}>{s.name}</option>)}</select>)}</>;
}
function Routine({project,program,onChange}:{project:Project;program:AutonomousProgram;onChange:(p:Program)=>void}){
 const [selected,setSelected]=useState<string>();
 const modify=(steps:Step[],id:string,fn:(s:Step)=>Step):Step[]=>steps.map(s=>s.id===id?fn(s):"steps"in s?{...s,steps:modify(s.steps,id,fn)}:s);
 const find=(steps:Step[]):Step|undefined=>{for(const s of steps){if(s.id===selected)return s;if("steps"in s){const f=find(s.steps);if(f)return f;}}};const chosen=find(program.routine);
 const edit=(fn:(s:Step)=>Step)=>onChange({...program,routine:modify(program.routine,selected!,fn)});
 const make=(kind:Step["kind"]):Step=>kind==="wait"?{id:newId("step"),kind,ms:250}:kind==="path"?{id:newId("step"),kind,pathId:program.paths[0]?.id??""}:kind==="state"?{id:newId("step"),kind,subsystemId:project.subsystems[0]?.id??"",stateId:project.subsystems[0]?.states[0]?.id??""}:{id:newId("step"),kind,steps:[]};
 const render=(steps:Step[],replace:(s:Step[])=>void):React.ReactNode=><ol className="flow-steps">{steps.map((s,i)=><li key={s.id} draggable onDragStart={e=>e.dataTransfer.setData("text/plain",s.id)} onDragOver={e=>e.preventDefault()} onDrop={e=>{e.preventDefault();e.stopPropagation();const from=steps.findIndex(x=>x.id===e.dataTransfer.getData("text/plain"));if(from>=0){const next=[...steps];next.splice(i,0,next.splice(from,1)[0]);replace(next);}}}><div className={`flow-step ${s.id===selected?"selected":""}`}><button className="step-select" onClick={()=>setSelected(s.id)}><small>{String(i+1).padStart(2,"0")}</small>{s.kind==="wait"?<Clock/>:s.kind==="path"?<Route/>:<GitBranch/>}<span><strong>{s.kind==="path"?program.paths.find(p=>p.id===s.pathId)?.name||"Choose a path":s.kind==="wait"?"Wait":s.kind==="state"?"Set mechanism state":s.kind==="together"?"Together":"Race"}</strong><small>{s.kind==="wait"?`${s.ms} ms`:s.kind==="path"?"Follow with Pedro Pathing":s.kind==="state"?project.subsystems.find(x=>x.id===s.subsystemId)?.states.find(x=>x.id===s.stateId)?.name:"Run child actions in parallel"}</small></span></button><div className="step-actions"><button aria-label={`Move action ${i+1} up`} disabled={i===0} onClick={()=>{const n=[...steps];[n[i-1],n[i]]=[n[i],n[i-1]];replace(n);}}><ArrowUp/></button><button aria-label={`Move action ${i+1} down`} disabled={i===steps.length-1} onClick={()=>{const n=[...steps];[n[i+1],n[i]]=[n[i],n[i+1]];replace(n);}}><ArrowDown/></button><button aria-label={`Duplicate action ${i+1}`} onClick={()=>replace([...steps.slice(0,i+1),cloneStep(s),...steps.slice(i+1)])}><Copy/></button><button aria-label={`Delete action ${i+1}`} onClick={()=>replace(steps.filter(x=>x.id!==s.id))}><Trash2/></button></div></div>{"steps"in s&&render(s.steps,children=>replace(steps.map(x=>x.id===s.id?{...s,steps:children}:x)))}</li>)}<li className="add-action"><select aria-label="Add action" value="" onChange={e=>{const s=make(e.target.value as Step["kind"]);replace([...steps,s]);setSelected(s.id);}}><option value="" disabled>＋ Add action</option><option value="path">Follow path</option><option value="wait">Wait</option><option value="state">Set mechanism state</option><option value="together">Together</option><option value="race">Race</option></select></li></ol>;
 return <div className="visual-editor"><div className="flow-canvas"><div className="flow-boundary">INIT</div>{render(program.routine,routine=>onChange({...program,routine}))}<div className="flow-boundary">STOP</div></div><aside className="properties"><h2>Properties</h2>{chosen?<><h3>{chosen.kind==="wait"?"Wait":chosen.kind==="path"?"Follow path":chosen.kind==="state"?"Mechanism state":"Parallel group"}</h3>{chosen.kind==="wait"?<NumberField label="Duration (ms)" value={chosen.ms} min={0} max={120000} step={50} onChange={ms=>edit(s=>({...s,ms}))}/>:chosen.kind==="path"?<label>Path<select value={chosen.pathId} onChange={e=>edit(s=>({...s,pathId:e.target.value}))}><option value="">Choose a path</option>{program.paths.map(p=><option value={p.id} key={p.id}>{p.name||"Unnamed path"}</option>)}</select></label>:chosen.kind==="state"?<><label>Mechanism<select value={chosen.subsystemId} onChange={e=>edit(s=>({...s,subsystemId:e.target.value,stateId:project.subsystems.find(x=>x.id===e.target.value)?.states[0]?.id??""}))}><option value="">Choose a mechanism</option>{project.subsystems.map(s=><option key={s.id} value={s.id}>{s.name}</option>)}</select></label><label>State<select value={chosen.stateId} onChange={e=>edit(s=>({...s,stateId:e.target.value}))}><option value="">Choose a state</option>{project.subsystems.find(s=>s.id===chosen.subsystemId)?.states.map(s=><option key={s.id} value={s.id}>{s.name}</option>)}</select></label></>:<p>{chosen.kind==="race"?"The first finished child ends this group and cancels the others.":"This group finishes after all its children finish."}</p>}<p>Actions run in order. Drag to reorder, or use the arrow buttons.</p></>:<p>Select an action to edit its properties.</p>}<hr/><label>Driver Station name<input value={program.name} onChange={e=>onChange({...program,name:e.target.value})}/></label><label>Group<input value={program.group} onChange={e=>onChange({...program,group:e.target.value})}/></label></aside></div>;
}
