import { lazy, Suspense, useCallback, useEffect, useMemo, useState } from "react";
import { ArrowLeft, BookOpen, Check, Code2, Command, Copy, Download, FolderOpen, GitBranch, Play, Plus, Redo2, Route, Trash2, Undo2, Wrench } from "lucide-react";
import { applyTunerOutput, createAutonomous, createTeleOp, findOpModes, generateJava, newId, ownershipOf, parseBuildOutput, updateTuningLocalizer, validateProject, type Project, type Program } from "../core";
import { isDesktop } from "../desktop/backend";
import { Modal } from "../components/ui/Modal";
import { Brand, Learn } from "./StudioApp";
import { ProgramEditor } from "./ProgramEditor";
import { FieldEditor } from "./FieldEditor";
import { Mechanisms } from "./Mechanisms";
import { Simulation } from "./Simulation";
import { useDesktop } from "./useDesktop";
import { DeployStatus, SdkConnection } from "./SdkConnection";
import { confirmAction, download, exportProject } from "./store";
const JavaEditor=lazy(()=>import("./JavaEditor"));
const TABS=[{id:"build",label:"Build",Icon:GitBranch},{id:"paths",label:"Paths",Icon:Route},{id:"code",label:"Code",Icon:Code2},{id:"simulate",label:"Simulate",Icon:Play},{id:"robot",label:"Robot",Icon:Wrench},{id:"learn",label:"Learn",Icon:BookOpen}] as const;
type Tab=typeof TABS[number]["id"];
export default function Workbench({project,onUpdate,onBack,saved}:{project:Project;onUpdate:(p:Project)=>void;onBack:()=>void;saved:string;onNotice:(s:string)=>void}){
 const [tab,setTab]=useState<Tab>("build"),[programId,setProgramId]=useState(project.programs[0]?.id),[notice,setNotice]=useState(""),[output,setOutput]=useState<string[]>([]),[bottom,setBottom]=useState("problems"),[filePath,setFilePath]=useState(""),[line,setLine]=useState<number>(),[palette,setPalette]=useState(false),[query,setQuery]=useState(""),[addProgram,setAddProgram]=useState(false),[newName,setNewName]=useState("New Auto"),[newKind,setNewKind]=useState("autonomous"),[license,setLicense]=useState(false),[host,setHost]=useState("192.168.43.1"),[tuner,setTuner]=useState<string|null>(null),[history,setHistory]=useState<{past:Project[];future:Project[]}>({past:[],future:[]});
 const log=useCallback((s:string)=>setOutput(lines=>[...lines.slice(-999),s]),[]);
 const desktop=useDesktop(project,log);
 const program=project.programs.find(p=>p.id===programId)??project.programs[0];
 const update=(p:Project)=>{setHistory(h=>({past:[...h.past.slice(-99),project],future:[]}));onUpdate(p);};
 const updateProgram=(p:Program)=>update({...project,programs:project.programs.map(x=>x.id===p.id?p:x)});
 const undo=()=>{const p=history.past[history.past.length-1];if(p){setHistory({past:history.past.slice(0,-1),future:[project,...history.future]});onUpdate(p);}};
 const redo=()=>{const p=history.future[0];if(p){setHistory({past:[...history.past,project],future:history.future.slice(1)});onUpdate(p);}};
 const generation=useMemo(()=>generateJava(project,desktop.target),[project,desktop.target?.javaPackage,desktop.target?.constantsClass]);const generated=generation.ok?generation.files:[];
 const problems=useMemo(()=>validateProject(project),[project]);const build=useMemo(()=>parseBuildOutput(output,desktop.folder),[output,desktop.folder]);
 const file=desktop.files.find(f=>f.path===filePath)??desktop.files[0];const generatedFile=generated.find(f=>f.path===filePath)??generated[0];const shown=desktop.folder?file:generatedFile;
 const [visualCode,setVisualCode]=useState(false);
 const selectedModes=shown?findOpModes(shown.content):[];
 useEffect(()=>{const keys=(e:KeyboardEvent)=>{if((e.ctrlKey||e.metaKey)&&e.key.toLowerCase()==="k"){e.preventDefault();setPalette(p=>!p);}if(e.key==="F5"&&e.shiftKey){e.preventDefault();desktop.cancel();}if((e.ctrlKey||e.metaKey)&&e.key.toLowerCase()==="z"&&!/INPUT|TEXTAREA/.test((e.target as HTMLElement).tagName)&&!(e.target as HTMLElement).closest(".monaco-editor")){e.preventDefault();if(e.shiftKey)redo();else undo();}};window.addEventListener("keydown",keys);return()=>window.removeEventListener("keydown",keys);});
 const commands=[...TABS.map(t=>({label:`Open ${t.label}`,run:()=>setTab(t.id)})),{label:"Undo",run:undo},{label:"Redo",run:redo},{label:"Export project",run:()=>exportProject(project)},...(isDesktop()?[{label:"Check Java",run:()=>{setBottom("output");void desktop.run("check");}},{label:"Connect FTC SDK project",run:()=>void desktop.connect()},...(desktop.folder?[{label:"Deploy code",run:()=>{setBottom("output");void desktop.deploy();}}]:[])]:[])];
 const codePane=<div className="java-workspace"><div className="file-explorer"><div className="section-title"><strong>{desktop.folder?"TeamCode":"Generated Java"}</strong></div>{(desktop.folder?desktop.files:generated).map(f=><button className={shown?.path===f.path?"active":""} key={f.path} title={f.path} onClick={()=>{setFilePath(f.path);setLine(undefined);}}><Code2/><span>{f.path.split("/").slice(-1)[0]}{"disk"in f&&f.content!==f.disk?" •":""}</span></button>)}</div><div className="java-main"><div className="java-toolbar"><span>{shown?.path.split("/").slice(-1)[0]??"No file selected"}</span><small>{desktop.folder?(shown&&ownershipOf(shown.content)==="generated"?"Generated · locked":"Team owned"):"Generated · read only"}</small>{shown&&<button onClick={()=>download(shown.path.split("/").slice(-1)[0]!,shown.content)}><Download/>Download</button>}{file&&desktop.folder&&<><button disabled={!!desktop.busy} onClick={()=>void desktop.save()}>Save files</button><button disabled={!!desktop.busy} onClick={()=>void desktop.reloadFile(file.path)}>Reload file</button>{ownershipOf(file.content)!=="team"&&<button onClick={()=>desktop.eject(file.path)}>Eject</button>}{file.path.endsWith("/Constants.java")&&<button onClick={()=>setTuner("")}>Paste AutoTune</button>}</>}</div>{shown?<Suspense fallback={<pre className="code-fallback">{shown.content}</pre>}><JavaEditor path={`${project.id}/${desktop.folder||"generated"}/${shown.path}`} value={shown.content} readOnly={!desktop.folder||ownershipOf(shown.content)==="generated"||!!desktop.busy} onChange={value=>desktop.edit(shown.path,value)} problems={build.problems.filter(p=>p.file===shown.path)} line={line}/></Suspense>:<div className="studio-empty"><Code2/><h2>Open your robot code</h2><p>{generation.ok?"Link an FTC project folder or create one below.":"Resolve the project problems to generate Java."}</p></div>}{selectedModes.length>0&&<div className="java-mode-list">OpModes: {selectedModes.map(m=>`${m.name}${m.disabled?" (disabled)":""}`).join(" · ")}</div>}</div></div>;
 return <div className="studio-workbench"><header className="studio-top"><button onClick={onBack} className="brand-home" aria-label="Back to projects"><Brand/></button><div className="breadcrumb"><span>Projects</span><span>/</span><input aria-label="Project name" value={project.name} onChange={e=>update({...project,name:e.target.value})}/><small><i className="status-dot"/>{saved}</small><DeployStatus desktop={desktop}/></div><div className="inline-actions"><button disabled={!history.past.length} onClick={undo} aria-label="Undo"><Undo2/></button><button disabled={!history.future.length} onClick={redo} aria-label="Redo"><Redo2/></button><button onClick={()=>setPalette(true)}><Command/><span>Commands</span></button><button aria-label="Help" onClick={()=>setTab("learn")}><BookOpen/></button></div></header>
 <aside className="studio-sidebar"><nav aria-label="Workspace">{TABS.map(({id,label,Icon})=><button key={id} className={id===tab?"active":""} onClick={()=>setTab(id)}><Icon/><span>{label}</span></button>)}</nav><div className="program-heading"><span>Programs</span><button aria-label="Add program" onClick={()=>setAddProgram(true)}><Plus/></button></div><nav aria-label="Programs">{project.programs.map(p=><button key={p.id} className={p.id===program?.id?"active":""} onClick={()=>setProgramId(p.id)}><GitBranch/><span>{p.name||"Unnamed program"}</span></button>)}</nav>{program&&<div className="program-actions"><button aria-label="Duplicate program" onClick={()=>{const copy={...structuredClone(program),id:newId("program"),name:`${program.name} copy`};update({...project,programs:[...project.programs,copy]});setProgramId(copy.id);}}><Copy/></button><button aria-label="Delete program" onClick={async()=>{if(await confirmAction(`Delete ${program.name}? You can undo this change.`))update({...project,programs:project.programs.filter(p=>p.id!==program.id)});}}><Trash2/></button></div>}<div className="sidebar-bottom"><small><i className="status-dot"/>Local workspace</small><button onClick={()=>exportProject(project)}><Download/><span>Export project</span></button><button onClick={onBack}><ArrowLeft/><span>All projects</span></button></div></aside>
 <main className="workbench-content"><header className="workbench-heading"><div><h1>{tab==="build"?"Program flow":tab==="paths"?"Path editor":tab==="code"?"Java editor":tab==="simulate"?"Simulate":tab==="robot"?"Robot setup":"Learn"}</h1><p>{program?`${program.kind==="autonomous"?"Autonomous":"TeleOp"} · ${program.name}`:"Add a program to get started."}</p></div><div className="inline-actions">{tab==="build"&&<div className="segmented"><button className={!visualCode?"active":""} onClick={()=>setVisualCode(false)}>Visual</button><button className={visualCode?"active":""} onClick={()=>setVisualCode(true)}>Code</button></div>}{isDesktop()?<><button disabled={!!desktop.busy||!desktop.folder} onClick={()=>{setBottom("output");void desktop.run("check");}}><Check/>Check</button><button disabled={!!desktop.busy||!desktop.folder} onClick={()=>{setBottom("output");void desktop.run("build");}}>Build APK</button></>:null}<button className="primary" onClick={()=>setTab("simulate")}><Play/>{isDesktop()?"Simulate":"Run preview"}</button></div></header>
 {notice&&<div className="studio-notice" role="alert">{notice}<button onClick={()=>setNotice("")}>Dismiss</button></div>}
 {tab==="code"&&isDesktop()&&<div className="desktop-bar">{desktop.folder?<><span title={desktop.folder}>{desktop.folder}</span><button disabled={!!desktop.busy} onClick={()=>{setBottom("output");void desktop.deploy();}}>Deploy code</button><button onClick={()=>setTab("robot")}>Deploy settings</button></>:<><button disabled={!!desktop.busy} onClick={()=>{setBottom("output");void desktop.connect();}}><FolderOpen/>Connect FTC SDK project</button><button disabled={!!desktop.busy} onClick={()=>{setBottom("output");void desktop.create();}}><Plus/>Create FTC project</button><span>No FTC SDK project connected</span></>}</div>}
 {tab==="code"&&isDesktop()&&!desktop.status?.ready&&<div className="toolchain-bar"><strong>Build tools</strong><span>{desktop.status?.missing.join(", ")||"Checking Java and Android SDK…"}</span>{desktop.status&&<><label className="check"><input type="checkbox" checked={license} onChange={e=>setLicense(e.target.checked)}/>I accept the <a href={desktop.status.install.licenseUrl} target="_blank" rel="noreferrer">Android SDK license</a></label><button disabled={!!desktop.busy||(!license&&desktop.status.missing.some(m=>m!=="java"))} onClick={()=>{setBottom("output");void desktop.install(license);}}>Install tools</button></>}</div>}
 <div className="workbench-surface">{tab==="build"?(program?(visualCode?codePane:<ProgramEditor project={project} program={program} onChange={updateProgram}/>):<div className="studio-empty"><h2>Your next program starts here.</h2><button onClick={()=>setAddProgram(true)}><Plus/>Add program</button></div>):tab==="paths"?(program?.kind==="autonomous"?<FieldEditor program={program} onChange={updateProgram} onNotice={setNotice}/>:<div className="studio-empty"><Route/><h2>Paths belong to autonomous programs</h2><p>Select or create an autonomous program to start drawing.</p></div>):tab==="code"?codePane:tab==="simulate"?(program?<Simulation key={program.id} project={project} program={program} launch={desktop.launch} busy={desktop.busy} cancel={desktop.cancel} onLog={log}/>:<p>Add a program first.</p>):tab==="robot"?<div className="editor-scroll"><SdkConnection desktop={desktop} project={project}/><h2>Robot connection</h2><div className="inline-actions"><label>Control Hub address<input value={host} onChange={e=>setHost(e.target.value)} placeholder="192.168.43.1"/></label><a href={`http://${host}:8001`} target="_blank" rel="noreferrer">Open Panels</a><a href={`http://${host}:10158`} target="_blank" rel="noreferrer">Open AutoTune</a>{isDesktop()&&<button className="primary" disabled={!!desktop.busy||!desktop.folder||!/^[\w.-]+$/.test(host)} onClick={()=>{setBottom("output");void desktop.run("deploy",host);}}>Deploy APK</button>}</div>{program&&<Simulation robot host={host} project={project} program={program} launch={desktop.launch} busy={desktop.busy} cancel={desktop.cancel} onLog={log}/>}<Mechanisms project={project} onChange={update}/></div>:<div className="editor-scroll"><Learn/></div>}</div>
 <section className="workbench-output"><div className="output-tabs"><button className={bottom==="problems"?"active":""} onClick={()=>setBottom("problems")}>Problems {problems.length+build.problems.length||""}</button><button className={bottom==="output"?"active":""} onClick={()=>setBottom("output")}>Output</button><span>{desktop.busy}</span>{desktop.busy&&<button className="danger" onClick={desktop.cancel}>Cancel task</button>}<button onClick={()=>setOutput([])}>Clear output</button></div><div className="output-body">{bottom==="output"?<pre aria-live="polite">{output.join("\n")||"Build and simulator output appears here."}</pre>:<>{!problems.length&&!build.problems.length?<p><i className="status-dot"/>No problems found.</p>:<>{problems.map((p,i)=><button className={`problem ${p.severity}`} key={i} onClick={()=>{if(p.location.programId)setProgramId(p.location.programId);setTab(p.location.pathId?"paths":"build");setVisualCode(false);}}>{p.severity}: {p.message}</button>)}{build.problems.map((p,i)=><button className="problem error" key={`build${i}`} onClick={()=>{if(p.file){setFilePath(p.file);setLine(p.line);setTab("code");}}}>{p.file}:{p.line} {p.message}</button>)}</>}</>}</div></section></main>
 <Modal open={palette} title="Commands" onClose={()=>setPalette(false)}><label>Search commands<input value={query} onChange={e=>setQuery(e.target.value)}/></label><div className="command-list">{commands.filter(c=>c.label.toLowerCase().includes(query.toLowerCase())).map(c=><button key={c.label} onClick={()=>{c.run();setPalette(false);setQuery("");}}>{c.label}</button>)}</div></Modal>
 <Modal open={addProgram} title="Add program" onClose={()=>setAddProgram(false)} footer={<><button onClick={()=>setAddProgram(false)}>Cancel</button><button className="primary" disabled={!newName.trim()} onClick={()=>{const p=newKind==="autonomous"?createAutonomous(newName.trim()):createTeleOp(newName.trim());update({...project,programs:[...project.programs,p]});setProgramId(p.id);setAddProgram(false);}}>Add program</button></>}><label>Program name<input value={newName} onChange={e=>setNewName(e.target.value)}/></label><label>Program type<select value={newKind} onChange={e=>setNewKind(e.target.value)}><option value="autonomous">Autonomous</option><option value="teleop">TeleOp</option></select></label></Modal>
 <Modal open={tuner!==null} title="Paste AutoTune results" onClose={()=>setTuner(null)} description="Review the updated Constants.java before saving. Localizer changes also update Tuning.java." footer={<><button onClick={()=>setTuner(null)}>Cancel</button><button className="primary" disabled={!tuner?.trim()} onClick={()=>{try{if(!file)return;const result=applyTunerOutput(file.content,tuner!);if(!result.replaced.length)throw new Error("No matching tuner declarations were found.");desktop.edit(file.path,result.source);const tuning=desktop.files.find(f=>f.path.endsWith("/pedro/Tuning.java"));if(result.localizerChange&&tuning)desktop.edit(tuning.path,updateTuningLocalizer(tuning.content,result.localizerChange));setNotice([...result.notes,...result.missing.map(m=>`Unmatched field: ${m}`),result.localizerChange&&!tuning?"Tuning.java was not found. Update its localizer type before building.":"","AutoTune results are staged in the editor. Review and save files."].filter(Boolean).join("\n"));setTuner(null);}catch(e){setNotice(String(e));}}}>Apply to editor</button></>}><label>AutoTune output<textarea rows={12} value={tuner??""} onChange={e=>setTuner(e.target.value)}/></label></Modal>
 </div>;
}
