use std::env;
use std::fmt::Write as _;
use std::fs;
use std::path::{Path, PathBuf};

fn main() {
    embed_repository_files();
    // tauri-build links its manifest into the app binary only; test binaries need it too.
    let windows = tauri_build::WindowsAttributes::new_without_app_manifest();
    tauri_build::try_build(tauri_build::Attributes::new().windows_attributes(windows))
        .expect("tauri-build");
    embed_windows_manifest();
}

fn embed_windows_manifest() {
    let msvc = env::var("CARGO_CFG_TARGET_OS").as_deref() == Ok("windows")
        && env::var("CARGO_CFG_TARGET_ENV").as_deref() == Ok("msvc");
    if msvc {
        let manifest = PathBuf::from(env::var("CARGO_MANIFEST_DIR").expect("CARGO_MANIFEST_DIR"))
            .join("windows-app-manifest.xml");
        println!("cargo:rerun-if-changed={}", manifest.display());
        println!("cargo:rustc-link-arg=/MANIFEST:EMBED");
        println!("cargo:rustc-link-arg=/MANIFESTINPUT:{}", manifest.display());
    }
}

/// Embeds the quickstart overlay, pinned upstream sources, and branding so the installed app can
/// create robot projects without this repository. Upstream code is still downloaded at runtime.
fn embed_repository_files() {
    let manifest = PathBuf::from(env::var("CARGO_MANIFEST_DIR").expect("CARGO_MANIFEST_DIR"));
    let repository = manifest.join("..").join("..");
    let overlay = repository.join("quickstart").join("overlay");
    let sources = repository.join("quickstart").join("sources.json");
    let brand = repository.join("app").join("src").join("brand.ts");
    let package = repository.join("app").join("package.json");
    let toolchain = manifest.join("toolchain.json");
    let robot = repository.join("robot");

    let mut files = Vec::new();
    collect(&overlay, &overlay, &mut files);
    files.sort();

    let mut code =
        String::from("// Generated by build.rs.\npub static OVERLAY: &[(&str, &[u8])] = &[\n");
    for (relative, absolute) in &files {
        writeln!(
            code,
            "    ({relative:?}, include_bytes!({:?})),",
            path_text(absolute)
        )
        .unwrap();
    }
    code.push_str("];\n");
    for (name, path) in [
        ("SOURCES_JSON", &sources),
        ("BRAND_TS", &brand),
        ("PACKAGE_JSON", &package),
        ("TOOLCHAIN_JSON", &toolchain),
    ] {
        writeln!(
            code,
            "pub static {name}: &str = include_str!({:?});",
            path_text(path)
        )
        .unwrap();
        println!("cargo:rerun-if-changed={}", path_text(path));
    }
    // Written into development projects' settings.gradle, matching scripts/quickstart.mjs.
    let robot = fs::canonicalize(&robot).unwrap_or(robot);
    let robot = path_text(&robot)
        .trim_start_matches(r"\\?\")
        .replace('\\', "/");
    writeln!(code, "pub static ROBOT_BUILD_DIR: &str = {robot:?};").unwrap();
    println!("cargo:rerun-if-changed={}", path_text(&overlay));

    let out = PathBuf::from(env::var("OUT_DIR").expect("OUT_DIR")).join("embedded.rs");
    fs::write(out, code).expect("write embedded.rs");
}

fn collect(root: &Path, directory: &Path, files: &mut Vec<(String, PathBuf)>) {
    let entries = fs::read_dir(directory)
        .unwrap_or_else(|error| panic!("read {}: {error}", directory.display()));
    for entry in entries {
        let path = entry.expect("directory entry").path();
        if path.is_dir() {
            collect(root, &path, files);
        } else {
            let relative = path.strip_prefix(root).expect("overlay path");
            let relative = relative
                .components()
                .map(|part| part.as_os_str().to_string_lossy())
                .collect::<Vec<_>>()
                .join("/");
            files.push((relative, path));
        }
    }
}

fn path_text(path: &Path) -> String {
    path.to_str()
        .expect("repository paths must be valid UTF-8")
        .to_owned()
}
