package dev.lumiere.ftc;

import static com.pedropathing.api.Paths.curve;
import static com.pedropathing.api.Paths.line;
import static com.pedropathing.api.Paths.path;
import static org.junit.Assert.assertEquals;
import static org.junit.Assert.assertTrue;

import com.pedropathing.math.Pose;
import com.pedropathing.paths.Path;
import com.pedropathing.paths.interpolator.Interpolator;

import dev.lumiere.ftc.internal.Json;

import org.junit.Test;

import java.io.File;
import java.nio.charset.StandardCharsets;
import java.nio.file.Files;
import java.util.ArrayList;
import java.util.List;
import java.util.Map;

/**
 * Builds the shared path cases with real Pedro Pathing paths and the {@link Headings} helpers, the
 * same way generated code does, and checks them against fixtures/parity/expected.json. The app's
 * TypeScript geometry is tested against the same file.
 *
 * <p>Run with the environment variable UPDATE_PARITY=1 to rewrite the expected values.
 */
public class HeadingsParityTest {
    private static final File FIXTURES = new File("../../fixtures/parity");
    private static final int SAMPLES = 20;

    @Test
    @SuppressWarnings("unchecked")
    public void pedroPathsMatchTheSharedFixture() throws Exception {
        Map<String, Object> input = Json.parseObject(read(new File(FIXTURES, "cases.json")));
        List<Object> results = new ArrayList<>();
        for (Object item : (List<Object>) input.get("cases")) {
            Map<String, Object> testCase = (Map<String, Object>) item;
            Map<String, Object> start = (Map<String, Object>) testCase.get("start");
            Path built = build(point(start), (Map<String, Object>) testCase.get("path"));
            List<Object> samples = new ArrayList<>();
            for (int i = 0; i <= SAMPLES; i++) {
                double t = (double) i / SAMPLES;
                Pose pose = built.get(t);
                samples.add(new double[]{t, pose.x(), pose.y(), built.heading(t), built.curve.remainingDistance(t)});
            }
            Map<String, Object> result = Json.object();
            result.put("name", testCase.get("name"));
            result.put("length", built.curve.length());
            result.put("samples", samples);
            results.add(result);
        }
        Map<String, Object> output = Json.object();
        output.put("$comment", "Generated by robot/ftc-lib HeadingsParityTest from cases.json. Samples are [t, x, y, headingRadians, remainingDistance].");
        output.put("cases", results);
        String text = Json.write(output);

        File expectedFile = new File(FIXTURES, "expected.json");
        if ("1".equals(System.getenv("UPDATE_PARITY")) || !expectedFile.exists()) {
            Files.write(expectedFile.toPath(), (text + "\n").getBytes(StandardCharsets.UTF_8));
        }
        Map<String, Object> expected = Json.parseObject(read(expectedFile));
        assertTrue("expected.json exists", expected != null);
        List<Object> expectedCases = (List<Object>) expected.get("cases");
        assertEquals(results.size(), expectedCases.size());
        Map<String, Object> actual = Json.parseObject(text);
        List<Object> actualCases = (List<Object>) actual.get("cases");
        for (int c = 0; c < actualCases.size(); c++) {
            Map<String, Object> want = (Map<String, Object>) expectedCases.get(c);
            Map<String, Object> got = (Map<String, Object>) actualCases.get(c);
            String name = (String) got.get("name");
            assertEquals(name, want.get("name"), got.get("name"));
            assertEquals(name + " length", (Double) want.get("length"), (Double) got.get("length"), 1e-9);
            List<Object> wantSamples = (List<Object>) want.get("samples");
            List<Object> gotSamples = (List<Object>) got.get("samples");
            for (int s = 0; s < gotSamples.size(); s++) {
                List<Object> w = (List<Object>) wantSamples.get(s);
                List<Object> g = (List<Object>) gotSamples.get(s);
                for (int k = 0; k < g.size(); k++) {
                    assertEquals(name + " sample " + s + " value " + k, (Double) w.get(k), (Double) g.get(k), 1e-9);
                }
            }
        }
    }

    @SuppressWarnings("unchecked")
    private static Path build(Pose start, Map<String, Object> doc) {
        if ("compound".equals(doc.get("kind"))) {
            List<Path> segments = new ArrayList<>();
            Pose segmentStart = start;
            for (Object item : (List<Object>) doc.get("segments")) {
                Map<String, Object> segment = (Map<String, Object>) item;
                segments.add(build(segmentStart, segment));
                segmentStart = point((Map<String, Object>) segment.get("end"));
            }
            Path compound = path(segments.toArray(new Path[0]));
            Object heading = doc.get("heading");
            return heading == null ? compound : withHeading(compound, (Map<String, Object>) heading);
        }
        Pose end = point((Map<String, Object>) doc.get("end"));
        List<Object> controls = (List<Object>) doc.get("controlPoints");
        Path geometry;
        if (controls.isEmpty()) {
            geometry = line(start, end);
        } else {
            Pose[] points = new Pose[controls.size() + 2];
            points[0] = start;
            for (int i = 0; i < controls.size(); i++) points[i + 1] = point((Map<String, Object>) controls.get(i));
            points[points.length - 1] = end;
            geometry = curve(points);
        }
        return withHeading(geometry, (Map<String, Object>) doc.get("heading"));
    }

    @SuppressWarnings("unchecked")
    private static Path withHeading(Path path, Map<String, Object> heading) {
        switch ((String) heading.get("type")) {
            case "linear":
                return path.heading(Headings.linear(radians(heading, "startDeg"), radians(heading, "endDeg")));
            case "constant":
                return path.constant(radians(heading, "degrees"));
            case "tangential":
                return Boolean.TRUE.equals(heading.get("reverse")) ? path.reverseTangent() : path.tangent();
            case "piecewise": {
                Headings.Piecewise builder = Headings.piecewise();
                for (Object item : (List<Object>) heading.get("segments")) {
                    Map<String, Object> segment = (Map<String, Object>) item;
                    double start = (Double) segment.get("startProgress");
                    double end = (Double) segment.get("endProgress");
                    switch ((String) segment.get("type")) {
                        case "linear": builder.linear(start, end, radians(segment, "startDeg"), radians(segment, "endDeg")); break;
                        case "constant": builder.constant(start, end, radians(segment, "degrees")); break;
                        case "tangential": builder.tangent(start, end, Boolean.TRUE.equals(segment.get("reverse"))); break;
                        case "facingPoint": {
                            Map<String, Object> target = (Map<String, Object>) segment.get("point");
                            builder.facingPoint(start, end, (Double) target.get("x"), (Double) target.get("y"));
                            break;
                        }
                        default: throw new IllegalArgumentException("Unknown segment " + segment.get("type"));
                    }
                }
                Interpolator interpolator = builder.build();
                return path.heading(interpolator);
            }
            default:
                throw new IllegalArgumentException("Unknown heading " + heading.get("type"));
        }
    }

    private static double radians(Map<String, Object> map, String key) {
        return Math.toRadians((Double) map.get(key));
    }

    private static Pose point(Map<String, Object> map) {
        return new Pose((Double) map.get("x"), (Double) map.get("y"));
    }

    private static String read(File file) throws Exception {
        return new String(Files.readAllBytes(file.toPath()), StandardCharsets.UTF_8);
    }
}
