/**
 * Reads an existing FTC SDK project (a FtcRobotController folder) to tell whether code generated by
 * the app will compile there: SDK version, required libraries, Pedro Pathing constants classes, and
 * the OpModes the team already has. Framework-free: callers pass the file contents in.
 */
import sources from "../../../../quickstart/sources.json";
import { TEAMCODE_JAVA_ROOT } from "../codegen/java/generate";
import { findOpModes, type OpModeDeclaration } from "../java/opModes";
import { maskJava, packageOf } from "../java/source";

/** Build files to read, relative to the project folder. Missing files are simply left out. */
export const INSPECTED_FILES = [
  "settings.gradle",
  "build.gradle",
  "build.common.gradle",
  "build.dependencies.gradle",
  "TeamCode/build.gradle",
  "TeamCode/libraries.gradle",
  "gradlew",
  "gradlew.bat",
] as const;

/** Every `.java` file below this folder is read as well. */
export const INSPECTED_JAVA_ROOT = TEAMCODE_JAVA_ROOT;

export const EXPECTED_SDK_VERSION = sources.versions.FTC_SDK_VERSION;

export interface FtcProjectSnapshot {
  /** Contents of the files that exist, keyed by project-relative path with forward slashes. */
  files: Map<string, string>;
}

export interface LibraryStatus {
  name: string;
  /** Maven group and artifact, such as `com.pedropathing:revhub`. */
  artifact: string;
  /** The version the generated code is built and tested with. */
  expected: string;
  /** The version declared by the project, or null when it is not declared. */
  found: string | null;
  ok: boolean;
}

export interface ConstantsClass {
  qualifiedName: string;
  path: string;
}

export interface FtcProjectInspection {
  /** True when the folder is an FTC SDK project that Gradle can build. */
  isFtcProject: boolean;
  /** Why the folder cannot be used; empty when `isFtcProject` is true. */
  problems: string[];
  sdkVersion: string | null;
  /** Libraries the generated code imports. */
  libraries: LibraryStatus[];
  librariesReady: boolean;
  /** Libraries in the project that conflict with the generated code, described for the team. */
  incompatible: string[];
  /** Classes with `static Follower create(HardwareMap)`, which generated OpModes call. */
  constantsClasses: ConstantsClass[];
  opModes: Array<OpModeDeclaration & { path: string }>;
  warnings: string[];
}

const LIBRARY_APPLY = /apply\s+from:\s*['"]libraries\.gradle['"]/;

function declaredVersion(gradle: string, artifact: string): string | null {
  const escaped = artifact.replace(/[.*+?^${}()|[\]\\]/g, "\\$&");
  return new RegExp(`['"]${escaped}:([^'"\\s]+)['"]`).exec(gradle)?.[1] ?? null;
}

const majorVersion = (version: string) => Number(/^v?(\d+)/.exec(version)?.[1] ?? NaN);

/** Gradle text that actually takes part in the TeamCode build. */
function activeGradle(files: Map<string, string>): string {
  const teamCode = files.get("TeamCode/build.gradle") ?? "";
  const parts = [files.get("build.dependencies.gradle") ?? "", files.get("build.gradle") ?? "", teamCode];
  // libraries.gradle only counts when TeamCode/build.gradle applies it.
  if (LIBRARY_APPLY.test(maskGradleComments(teamCode))) parts.push(files.get("TeamCode/libraries.gradle") ?? "");
  return parts.map(maskGradleComments).join("\n");
}

/** Gradle comments use the same syntax as Java; strings are kept so coordinates stay readable. */
function maskGradleComments(text: string): string {
  return text.replace(/\/\*[\s\S]*?\*\//g, " ").replace(/(^|[^:'"])\/\/.*$/gm, "$1");
}

export function inspectFtcProject(snapshot: FtcProjectSnapshot): FtcProjectInspection {
  const { files } = snapshot;
  const problems: string[] = [];
  const warnings: string[] = [];
  if (!files.has("TeamCode/build.gradle")) problems.push("This folder has no TeamCode module. Choose the FtcRobotController folder that contains TeamCode.");
  if (!files.has("gradlew") && !files.has("gradlew.bat")) problems.push("This folder has no Gradle wrapper (gradlew). Choose the top folder of the FTC SDK project.");

  const gradle = activeGradle(files);
  const sdkVersion = declaredVersion(gradle, "org.firstinspires.ftc:RobotCore");
  if (!problems.length && !sdkVersion) warnings.push("The FTC SDK version could not be read from build.dependencies.gradle.");
  if (sdkVersion && sdkVersion !== EXPECTED_SDK_VERSION) {
    warnings.push(`This project uses FTC SDK ${sdkVersion}. Generated code is built and tested with FTC SDK ${EXPECTED_SDK_VERSION}.`);
  }

  const robotLibrary = /['"]([\w.-]+):ftc-lib:([^'"\s]+)['"]/.exec(gradle);
  const libraries: LibraryStatus[] = [
    { name: "Pedro Pathing", artifact: "com.pedropathing:revhub", expected: sources.versions.PEDRO_VERSION },
    { name: "Ivy commands", artifact: "com.pedropathing.ivy:core", expected: sources.versions.IVY_VERSION },
    { name: "Ivy Pedro Pathing commands", artifact: "com.pedropathing.ivy:pedro", expected: sources.versions.IVY_VERSION },
  ].map((library) => {
    const found = declaredVersion(gradle, library.artifact);
    return { ...library, found, ok: found !== null && majorVersion(found) === majorVersion(library.expected) };
  });
  libraries.push({
    name: "Robot library (live data and headings)",
    artifact: robotLibrary ? `${robotLibrary[1]}:ftc-lib` : "ftc-lib",
    expected: "matching this app",
    found: robotLibrary?.[2] ?? null,
    ok: robotLibrary !== null,
  });

  const incompatible: string[] = [];
  for (const artifact of ["com.pedropathing:ftc", "com.pedropathing:pedro", "com.pedropathing:core"]) {
    const version = declaredVersion(gradle, artifact);
    if (version && majorVersion(version) < 3) {
      incompatible.push(`${artifact}:${version} is Pedro Pathing ${majorVersion(version)}. Generated code needs Pedro Pathing 3, whose API is different. Update the project to Pedro Pathing 3 first.`);
    }
  }
  const revhub = libraries[0];
  if (revhub.found && !revhub.ok) incompatible.push(`com.pedropathing:revhub:${revhub.found} is not Pedro Pathing 3.`);

  const constantsClasses: ConstantsClass[] = [];
  const opModes: FtcProjectInspection["opModes"] = [];
  for (const [path, content] of files) {
    if (!path.startsWith(`${INSPECTED_JAVA_ROOT}/`) || !path.endsWith(".java")) continue;
    const masked = maskJava(content);
    if (/\bstatic\s+(?:final\s+)?Follower\s+create\s*\(\s*(?:final\s+)?HardwareMap\s+\w+\s*\)/.test(masked)) {
      const className = /\bclass\s+([A-Za-z_$][\w$]*)/.exec(masked)?.[1];
      const packageName = packageOf(content);
      if (className && packageName) constantsClasses.push({ qualifiedName: `${packageName}.${className}`, path });
    }
    for (const opMode of findOpModes(content)) opModes.push({ ...opMode, path });
  }
  constantsClasses.sort((a, b) => a.qualifiedName.localeCompare(b.qualifiedName));
  opModes.sort((a, b) => a.path.localeCompare(b.path) || a.line - b.line);

  return {
    isFtcProject: problems.length === 0,
    problems,
    sdkVersion,
    libraries,
    librariesReady: libraries.every((library) => library.ok) && incompatible.length === 0,
    incompatible,
    constantsClasses,
    opModes,
    warnings,
  };
}
